### ISSUE TITLE
Parsing script error

### ISSUE THREAD

**Issue by Net-Mist** [dimfeld/export-logseq-notes#12]
Hello, thanks a lot for this great project !

When trying to run it (master branch, no changes except data path in `export-logseq-notes.toml`), I got this error:
```
Error:
   0: Parsing script
   1: Syntax error: Expression exceeds maximum complexity (line 40, position 41)
```
Any idea why ?

**Comment by dimfeld** [comment]
Hmm, that is very strange. I can't seem to reproduce that on my end. 

I just pushed a commit to upgrade some dependencies, which includes a newer version of the `rhai` scripting engine. Not sure if it will help since both the older version and the latest work fine for me, but might be worth a try.

**Comment by dimfeld** [comment]
Seems like it could be related to https://rhai.rs/book/safety/max-stmt-depth.html. Can you try it with a release build? If that works then perhaps I just need to raise the limit referenced there.

**Comment by Net-Mist** [comment]
Thanks for your feedback ! It seems updating the dependencies solved the issue. Also running in release mode doesn't trigger the issue before this fix.
-  On commit 1ea8fd6:  
	- `cargo run --release` => works
	- `cargo run` => doesn't work
- On commit aa7c12e (current master) => both work

Thanks a lot!
